# Generated by Django 3.0 on 2020-09-07 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultstest',
            name='status',
            field=models.CharField(choices=[('1', 'active'), ('0', 'deactive')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='quizcopy1',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 15, 46, 40, 532687)),
        ),
        migrations.AlterField(
            model_name='quizcopy2',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 15, 46, 40, 533249)),
        ),
    ]
