# Generated by Django 3.0.8 on 2020-08-01 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='quizcopy1',
            name='student_choices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizcopy2',
            name='student_choices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
