# Generated by Django 3.0.8 on 2020-09-27 09:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultstest',
            name='quiz',
        ),
        migrations.AddField(
            model_name='resultstest',
            name='quiz1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizCopy1'),
        ),
        migrations.AddField(
            model_name='resultstest',
            name='quiz2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizCopy2'),
        ),
        migrations.AlterField(
            model_name='quizcopy1',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 16, 25, 14, 913145)),
        ),
        migrations.AlterField(
            model_name='quizcopy2',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 16, 25, 14, 914174)),
        ),
    ]
