# Generated by Django 3.0.8 on 2020-10-12 14:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200927_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcopy1',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 12, 21, 36, 6, 753547)),
        ),
        migrations.AlterField(
            model_name='quizcopy2',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 12, 21, 36, 6, 753547)),
        ),
        migrations.CreateModel(
            name='QuestionCopy2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('explain', models.TextField(blank=True, null=True)),
                ('choices', models.TextField()),
                ('correct_choices', models.TextField()),
                ('quiz2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizCopy2')),
            ],
            options={
                'db_table': 'questions_copy2',
            },
        ),
    ]
