# Generated by Django 3.0 on 2020-08-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200820_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('1', 'active'), ('0', 'deactive')], default='0', max_length=1),
        ),
    ]
