# Generated by Django 3.0.8 on 2020-10-12 14:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201012_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcopy2',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizcopy1',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 12, 21, 46, 57, 274470)),
        ),
        migrations.AlterField(
            model_name='quizcopy2',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 12, 21, 46, 57, 274470)),
        ),
    ]
