# Generated by Django 3.0.8 on 2020-12-11 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201023_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='admin',
        ),
        migrations.AlterField(
            model_name='quizcopy1',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 23, 38, 9, 670653)),
        ),
        migrations.AlterField(
            model_name='quizcopy2',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 23, 38, 9, 671650)),
        ),
    ]
