# Generated by Django 3.0.8 on 2020-12-11 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20201211_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='active',
            new_name='admin',
        ),
        migrations.AlterField(
            model_name='quizcopy1',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 23, 38, 33, 860331)),
        ),
        migrations.AlterField(
            model_name='quizcopy2',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 23, 38, 33, 861329)),
        ),
    ]
